<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current PrCodes_prcodes</name>
   <tag></tag>
   <elementGuidId>a30a8e9f-ef8e-44b1-9d51-d46a42e3229d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'prcodes']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prcodes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>F14 Q0D9,GP21P21,GPC5PC5,GPJ0PJ0,GPN1PN1,GPN3PN3,GPN4PN4,GW10W10,GW11W11,GW12W12,GWV1WV1,GWV4WV4,GY01Y01,GY11Y11,GY37Y37,GYCSYCS,GYD5YD5,GYECYEC,GYMHYMH,GYMKYMK,GYRMYRM,GZCNZCN,GZITZIT,JAZMGT,JAZMMA,JAZMMB,JAZMME,JBZANA,JCANNA,JCONMA,JCONMB,JCONME,JCONNA,JDORGT,JDORMA,JDORMB,JDORME,JFBCME,JFBCNA,JFCCGT,JFCCMA,JFCCMB,JFCCME,JFCINA,JFCUGT,JFCUIN,JFCUNA,JFCUNO,JFTANA,JHDLNA,JSBTNA,JSEINA,JWCRNA,MAAUE0A,MABO6H3,MABR1PH,MAED7LS,MAER0P0,MAGM7MM,MAIB4UF,MALGQE0,MASE6XE,MASGEA0,MASL5SJ,MASR5RU,MAUD9WT,MAUSA8S,MBAH2EG,MBAV1LD,MBBO6FI,MBEH4M0,MBFA0UA,MBFA0UF,MBFA0UK,MBLBB0A,MBLEKN2,MBOW1S0,MBTA7YH,MCOCC00,MCPDIW0,MDAE2MP,MDEKGT2,MDFO6F5,MDPF4XD,MDPF4XG,MEDW7AL,MEIH7TH,MEIUQ8A,MEMINR7,MEPH7X9,MFEU6A7,MFIT6RC,MFLS8K4,MFVS7G1,MFZSF0A,MGMOTC9,MGNF4U0,MGRTVC1,MGRV5A4,MGSPG1H,MHAK4Z1,MHES5J8,MHIA0N5,MHIM6NJ,MHIM6NL,MHIM6NP,MHIM6NR,MHIM6NT,MHIM6NV,MHSW8ED,MINSU0F,MKAE0KA,MKARK8C,MKRS1A0,MKSA5C6,MKSI3G0,MKUHKK3,MLAC5K2,MLAKFB7,MLCPQQ2,MLEAL0L,MLEN1N8,MLFFVK1,MLRA2PP,MLSE9VK,MLUM7HB,MMADNM5,MMFA9Q1,MMIK3D3,MMJZIY1,MMOTD84,MNAV7Q2,MPAMGP1,MPRSFR9,MQUAAQ0,MRADU67,MRAO8AJ,MRAU9JA,MRDK7K1,MREIH2M,MRER1G8,MSAANU2,MSAD2HA,MSFS2K0,MSIBN0K,MSIBN0R,MSIBN2R,MSIBN3N,MSIBN3Q,MSIBN6E,MSIBN7S,MSIBN7U,MSIE3L5,MSIH4A3,MSLE8F0,MSNA7L6,MSSL4B1,MSSP05Z,MSVOFA0,MTPLB14,MTRF5D7,MTSPNT0,MTVEQV0,MTYP1EX,MVGP5GZ,MVOSQ1D,MVTV9ZF,MWABVD0,MWIN7S0,MZBR2WA,MZFM0TC,MZIE4ZC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prcodes&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//input[@id='prcodes']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='ZlLeftAppTabComponent']/div/div[3]/section/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current PrCodes'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prcode Configuration'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Configuration'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved configurations'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
